// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_types.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveActivityType = `-- name: ArchiveActivityType :one
UPDATE activity_types
SET archived_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, group_id, name, description, default_duration_minutes, color, archived_at, created_at, updated_at
`

type ArchiveActivityTypeParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) ArchiveActivityType(ctx context.Context, arg ArchiveActivityTypeParams) (ActivityType, error) {
	row := q.db.QueryRow(ctx, archiveActivityType, arg.ID, arg.UserID)
	var i ActivityType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.DefaultDurationMinutes,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createActivityType = `-- name: CreateActivityType :one
INSERT INTO activity_types (user_id, group_id, name, description, default_duration_minutes, color)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, group_id, name, description, default_duration_minutes, color, archived_at, created_at, updated_at
`

type CreateActivityTypeParams struct {
	UserID                 pgtype.UUID `json:"user_id"`
	GroupID                pgtype.UUID `json:"group_id"`
	Name                   string      `json:"name"`
	Description            *string     `json:"description"`
	DefaultDurationMinutes *int32      `json:"default_duration_minutes"`
	Color                  *string     `json:"color"`
}

func (q *Queries) CreateActivityType(ctx context.Context, arg CreateActivityTypeParams) (ActivityType, error) {
	row := q.db.QueryRow(ctx, createActivityType,
		arg.UserID,
		arg.GroupID,
		arg.Name,
		arg.Description,
		arg.DefaultDurationMinutes,
		arg.Color,
	)
	var i ActivityType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.DefaultDurationMinutes,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivityType = `-- name: GetActivityType :one
SELECT id, user_id, group_id, name, description, default_duration_minutes, color, archived_at, created_at, updated_at FROM activity_types WHERE id = $1 AND user_id = $2
`

type GetActivityTypeParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetActivityType(ctx context.Context, arg GetActivityTypeParams) (ActivityType, error) {
	row := q.db.QueryRow(ctx, getActivityType, arg.ID, arg.UserID)
	var i ActivityType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.DefaultDurationMinutes,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivityTypes = `-- name: ListActivityTypes :many
SELECT id, user_id, group_id, name, description, default_duration_minutes, color, archived_at, created_at, updated_at FROM activity_types
WHERE user_id = $1
    AND ($2::uuid IS NULL OR group_id = $2)
    AND ($3::bool OR archived_at IS NULL)
ORDER BY created_at
`

type ListActivityTypesParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	GroupID         pgtype.UUID `json:"group_id"`
	IncludeArchived bool        `json:"include_archived"`
}

func (q *Queries) ListActivityTypes(ctx context.Context, arg ListActivityTypesParams) ([]ActivityType, error) {
	rows, err := q.db.Query(ctx, listActivityTypes, arg.UserID, arg.GroupID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityType
	for rows.Next() {
		var i ActivityType
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Name,
			&i.Description,
			&i.DefaultDurationMinutes,
			&i.Color,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivityType = `-- name: UpdateActivityType :one
UPDATE activity_types
SET
    name = COALESCE($3, name),
    description = COALESCE($4, description),
    default_duration_minutes = COALESCE($5, default_duration_minutes),
    color = COALESCE($6, color),
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, group_id, name, description, default_duration_minutes, color, archived_at, created_at, updated_at
`

type UpdateActivityTypeParams struct {
	ID                     pgtype.UUID `json:"id"`
	UserID                 pgtype.UUID `json:"user_id"`
	Name                   *string     `json:"name"`
	Description            *string     `json:"description"`
	DefaultDurationMinutes *int32      `json:"default_duration_minutes"`
	Color                  *string     `json:"color"`
}

func (q *Queries) UpdateActivityType(ctx context.Context, arg UpdateActivityTypeParams) (ActivityType, error) {
	row := q.db.QueryRow(ctx, updateActivityType,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.DefaultDurationMinutes,
		arg.Color,
	)
	var i ActivityType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.DefaultDurationMinutes,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
