// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActivityTypesInGroup = `-- name: CountActivityTypesInGroup :one
SELECT count(*) FROM activity_types WHERE group_id = $1
`

func (q *Queries) CountActivityTypesInGroup(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityTypesInGroup, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (user_id, name, color, icon)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, color, icon, is_default, created_at, updated_at
`

type CreateGroupParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Color  *string     `json:"color"`
	Icon   *string     `json:"icon"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.UserID,
		arg.Name,
		arg.Color,
		arg.Icon,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM groups WHERE id = $1 AND user_id = $2
`

type DeleteGroupParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroup, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGroup = `-- name: GetGroup :one
SELECT id, user_id, name, color, icon, is_default, created_at, updated_at FROM groups WHERE id = $1 AND user_id = $2
`

type GetGroupParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetGroup(ctx context.Context, arg GetGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, arg.ID, arg.UserID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroups = `-- name: ListGroups :many
SELECT id, user_id, name, color, icon, is_default, created_at, updated_at FROM groups
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListGroups(ctx context.Context, userID pgtype.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.Icon,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET
    name = COALESCE($3, name),
    color = COALESCE($4, color),
    icon = COALESCE($5, icon),
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, color, icon, is_default, created_at, updated_at
`

type UpdateGroupParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   *string     `json:"name"`
	Color  *string     `json:"color"`
	Icon   *string     `json:"icon"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Color,
		arg.Icon,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
