// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityType struct {
	ID                     pgtype.UUID        `json:"id"`
	UserID                 pgtype.UUID        `json:"user_id"`
	GroupID                pgtype.UUID        `json:"group_id"`
	Name                   string             `json:"name"`
	Description            *string            `json:"description"`
	DefaultDurationMinutes *int32             `json:"default_duration_minutes"`
	Color                  *string            `json:"color"`
	ArchivedAt             pgtype.Timestamptz `json:"archived_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type Group struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Color     *string            `json:"color"`
	Icon      *string            `json:"icon"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PlannedOccurrence struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	SeriesID           pgtype.UUID        `json:"series_id"`
	ActivityTypeID     pgtype.UUID        `json:"activity_type_id"`
	OccurrenceDate     pgtype.Date        `json:"occurrence_date"`
	StartAt            pgtype.Timestamptz `json:"start_at"`
	EndAt              pgtype.Timestamptz `json:"end_at"`
	IsOverridden       bool               `json:"is_overridden"`
	IsCanceled         bool               `json:"is_canceled"`
	NotificationSentAt pgtype.Timestamptz `json:"notification_sent_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type PlannedSeries struct {
	ID                      pgtype.UUID        `json:"id"`
	UserID                  pgtype.UUID        `json:"user_id"`
	ActivityTypeID          pgtype.UUID        `json:"activity_type_id"`
	StartDate               pgtype.Date        `json:"start_date"`
	StartTime               pgtype.Time        `json:"start_time"`
	DurationMinutes         int32              `json:"duration_minutes"`
	RecurrenceFrequency     *string            `json:"recurrence_frequency"`
	RecurrenceInterval      *int32             `json:"recurrence_interval"`
	RecurrenceWeekdays      []int16            `json:"recurrence_weekdays"`
	RecurrenceMonthDay      *int32             `json:"recurrence_month_day"`
	RecurrenceWeekOrdinal   *int32             `json:"recurrence_week_ordinal"`
	RecurrenceWeekday       *int16             `json:"recurrence_weekday"`
	RecurrenceEndType       *string            `json:"recurrence_end_type"`
	RecurrenceEndDate       pgtype.Date        `json:"recurrence_end_date"`
	RecurrenceEndCount      *int32             `json:"recurrence_end_count"`
	NotificationLeadMinutes *int32             `json:"notification_lead_minutes"`
	CanceledFromDate        pgtype.Date        `json:"canceled_from_date"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type TimeLog struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	ActivityTypeID      pgtype.UUID        `json:"activity_type_id"`
	StartAt             pgtype.Timestamptz `json:"start_at"`
	EndAt               pgtype.Timestamptz `json:"end_at"`
	Note                *string            `json:"note"`
	PlannedOccurrenceID pgtype.UUID        `json:"planned_occurrence_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                      pgtype.UUID        `json:"id"`
	ClerkUserID             string             `json:"clerk_user_id"`
	Email                   string             `json:"email"`
	Timezone                string             `json:"timezone"`
	NotificationLeadMinutes int32              `json:"notification_lead_minutes"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}
