// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveActivityType(ctx context.Context, arg ArchiveActivityTypeParams) (ActivityType, error)
	CountActivityTypesInGroup(ctx context.Context, groupID pgtype.UUID) (int64, error)
	CreateActivityType(ctx context.Context, arg CreateActivityTypeParams) (ActivityType, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	DeleteGroup(ctx context.Context, arg DeleteGroupParams) (int64, error)
	GetActivityType(ctx context.Context, arg GetActivityTypeParams) (ActivityType, error)
	GetGroup(ctx context.Context, arg GetGroupParams) (Group, error)
	GetUserByClerkID(ctx context.Context, clerkUserID string) (User, error)
	ListActivityTypes(ctx context.Context, arg ListActivityTypesParams) ([]ActivityType, error)
	ListGroups(ctx context.Context, userID pgtype.UUID) ([]Group, error)
	UpdateActivityType(ctx context.Context, arg UpdateActivityTypeParams) (ActivityType, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (User, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
