// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, clerk_user_id, email, timezone, notification_lead_minutes, created_at, updated_at FROM users WHERE clerk_user_id = $1
`

func (q *Queries) GetUserByClerkID(ctx context.Context, clerkUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkID, clerkUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.Timezone,
		&i.NotificationLeadMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE users
SET
    timezone = COALESCE($2, timezone),
    notification_lead_minutes = COALESCE($3, notification_lead_minutes),
    updated_at = now()
WHERE id = $1
RETURNING id, clerk_user_id, email, timezone, notification_lead_minutes, created_at, updated_at
`

type UpdateUserSettingsParams struct {
	ID                      pgtype.UUID `json:"id"`
	Timezone                *string     `json:"timezone"`
	NotificationLeadMinutes *int32      `json:"notification_lead_minutes"`
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSettings, arg.ID, arg.Timezone, arg.NotificationLeadMinutes)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.Timezone,
		&i.NotificationLeadMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (clerk_user_id, email)
VALUES ($1, $2)
ON CONFLICT (clerk_user_id) DO UPDATE SET
    email = EXCLUDED.email,
    updated_at = now()
RETURNING id, clerk_user_id, email, timezone, notification_lead_minutes, created_at, updated_at
`

type UpsertUserParams struct {
	ClerkUserID string `json:"clerk_user_id"`
	Email       string `json:"email"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.ClerkUserID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.Timezone,
		&i.NotificationLeadMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
